before:
  hooks:
    - make release

builds:
- id: "clusterctl-operator"
  main: ./cmd/plugin
  binary: bin/clusterctl-operator
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
archives:
- id: clusterctl-operator
  builds:
  - clusterctl-operator
  name_template: "clusterctl-operator_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: false
