builds:
- id: "clusterctl-operator"
  main: ./cmd/plugin
  binary: bin/clusterctl-operator
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
  - goos: windows
    goarch: ppc64le
archives:
- id: clusterctl-operator
  builds:
  - clusterctl-operator
  name_template: "clusterctl-operator_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  prerelease: auto
  mode: keep-existing

krews:
- name: operator
  ids:
  - clusterctl-operator
  repository:
    owner: Danil-Grigorev
    name: cluster-api-operator
    branch: test
    token: "{{ .Env.GITHUB_TOKEN }}"
    pull_request:
      # Whether to enable it or not.
      enabled: true
  description: |
    Use this clusterctl plugin to bootstrap a management cluster for Cluster API with the Cluster API Operator.
  short_description: "Use this clusterctl plugin to bootstrap a management cluster for Cluster API with the Cluster API Operator."
  skip_upload: auto
