# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.cluster.x-k8s.io_coreproviders.yaml
- bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
- bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
- bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
- bases/operator.cluster.x-k8s.io_addonproviders.yaml
- bases/operator.cluster.x-k8s.io_ipamproviders.yaml
- bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_coreproviders.yaml
- path: patches/webhook_in_bootstrapproviders.yaml
- path: patches/webhook_in_controlplaneproviders.yaml
- path: patches/webhook_in_infrastructureproviders.yaml
- path: patches/webhook_in_addonproviders.yaml
- path: patches/webhook_in_ipamproviders.yaml
- path: patches/webhook_in_runtimeextensionproviders.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_coreproviders.yaml
- path: patches/cainjection_in_bootstrapproviders.yaml
- path: patches/cainjection_in_controlplaneproviders.yaml
- path: patches/cainjection_in_infrastructureproviders.yaml
- path: patches/cainjection_in_addonproviders.yaml
- path: patches/cainjection_in_ipamproviders.yaml
- path: patches/cainjection_in_runtimeextensionproviders.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
