name: release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write # Allow to create a release.

jobs:
  release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run:  echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Generate release artifacts
        run: |
          make release
      - name: Create draft GH release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            out/operator-components.yaml
            out/package/*
          body: "TODO: Add release notes here."

  release-plugin:
    needs: release
    name: Create plugin release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: cytopia/upload-artifact-retry-action@v0.1.2
        if: ${{ always() }}
        with:
          name: binaries
          path: dist/*.tar.gz
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.46
        env:
          UPSTREAM_KREW_INDEX_REPO_NAME: cluster-api-operator
          UPSTREAM_KREW_INDEX_REPO_OWNER: Danil-Grigorev
